@startuml
'https://plantuml.com/sequence-diagram

start

:Пользователь нажал на кнопку Play;
:Кнопка сменилась на Stop;
:Программа начала записывать голос с микрофона;
:Включился таймер;
:Пользователь нажал на кнопку Stop;
:Таймер остановился;
:Программа сохранила записанный голос в формате аудио и передала расшифровщику;
:Расшифровщик вернул распознанный текст;
:Распознанный текст отобразился на экране;
end
@enduml